version: '3.3'

services:
  django:
    build: ./backend
    command: "gunicorn backend.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - /static:/static
      - /media:/media
    env_file:
      - '.env'
    ports:
      - '8000:8000'

volumes:
  static_volume:
  media_volume:
