# Generated by Django 4.1.3 on 2022-11-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUIZ', 'Опрос'), ('TEST', 'Тестирование')], max_length=120, verbose_name='Тип формы')),
                ('name', models.TextField(verbose_name='Название тестирования/опроса')),
                ('plank', models.IntegerField(blank=True, default=0, verbose_name='Количество баллов для прохождения тестов')),
                ('success_text', models.TextField(verbose_name='Успешный итоговый текст')),
                ('failure_text', models.TextField(verbose_name='Провальный итоговый текст')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0, verbose_name='В общем баллов')),
                ('passed', models.BooleanField(blank=True, default=0, verbose_name='Пройдено или нет')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Связанный опрос/тестирование')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('RADIO', 'Один из множества'), ('CHECKBOX', 'Несколько вариантов'), ('OPEN', 'Открытый')], max_length=120, verbose_name='Тип вопроса')),
                ('reward', models.IntegerField(blank=True, default=0, verbose_name='Баллы за правильный ответ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Связанный опрос/тестирование')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_variant', models.TextField(verbose_name='Вариант ответа')),
                ('is_right', models.BooleanField(default=0, verbose_name='Правильный или нет')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion', verbose_name='Связанный опрос/тестирование')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswerChoosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(blank=True, default=0, verbose_name='Выбрано правильно или нет')),
                ('text', models.TextField(blank=True, default='', verbose_name='Ответ на открытый вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion', verbose_name='Связанный вопрос')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizresult', verbose_name='Связанный общий результат')),
            ],
        ),
    ]
