# Generated by Django 4.1.3 on 2022-11-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('preview', models.ImageField(upload_to='partners/previews', verbose_name='Превью компании')),
                ('banner', models.ImageField(upload_to='partners/banners', verbose_name='Баннер компании')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=1, verbose_name='Компания активна')),
                ('show_on_main', models.BooleanField(default=1, verbose_name='Отображать на главной')),
            ],
        ),
    ]
