# Generated by Django 4.1.3 on 2022-11-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
                ('text', models.TextField(verbose_name='Текст')),
                ('url', models.TextField(verbose_name='Ссылка (источник)')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_image', verbose_name='Картинка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article', verbose_name='Новость')),
            ],
        ),
    ]
