# Generated by Django 4.1.3 on 2022-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, verbose_name='Ссылка (источник)'),
        ),
    ]
