# Generated by Django 4.1.3 on 2022-11-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_staffpins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('STAFF', 'Работник')], max_length=120, verbose_name='Пользователь или гражданин'),
        ),
    ]
